package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Domingo, 10 de Novembro de 2024 23h54min10s BOT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
